#!/bin/bash -efu

cwd="$(readlink -ev "$0")"
cwd="${cwd%/*}"
bin="$cwd/.."

workdir=
exit_handler()
{
	trap - EXIT
	[ -z "$workdir" ] ||
		rm -rf -- "$workdir" ||:
	exit "$1"
}

trap 'exit_handler $?' HUP PIPE INT QUIT TERM EXIT
workdir=$(mktemp -d -t ts.XXXXXX)

echo "### init"
cd "$workdir"
touch somefile

git init --quiet -b master
git add .
git commit -q -a -m 'first commit'

for name in foo bar baz; do
	echo "### creating $name"
	"$bin"/git-patchset create --no-edit-cover "$name" -S master

	echo "### new minor version (1)"
	"$bin"/git-patchset version

	echo "### new minor version (2)"
	"$bin"/git-patchset version

	echo "### new major version (1)"
	"$bin"/git-patchset version --major

	echo "### new major version (2)"
	"$bin"/git-patchset version --major
done

echo "### archive foo"
"$bin"/git-patchset archive --add foo/v2.0

echo "### archive bar"
"$bin"/git-patchset archive --add bar

echo "### default list"
"$bin"/git-patchset |
	sed -r -e 's/ [0-9a-f]+\.\.[0-9a-f]+ / aaaaaaa..bbbbbbb /'

echo "### list of patchsets"
"$bin"/git-patchset list --all |
	sed -r -e 's/ [0-9a-f]+\.\.[0-9a-f]+ / aaaaaaa..bbbbbbb /'

echo "### list of latest patchsets"
"$bin"/git-patchset list --latest |
	sed -r -e 's/ [0-9a-f]+\.\.[0-9a-f]+ / aaaaaaa..bbbbbbb /'

echo "### list of foo verions"
"$bin"/git-patchset list --versions |
	sed -r -e 's/ [0-9a-f]+\.\.[0-9a-f]+ / aaaaaaa..bbbbbbb /'

echo "### list of latest versions in archive"
"$bin"/git-patchset list --archive |
	sed -r -e 's/ [0-9a-f]+\.\.[0-9a-f]+ / aaaaaaa..bbbbbbb /'

echo "### list of archive"
"$bin"/git-patchset list --all --archive |
	sed -r -e 's/ [0-9a-f]+\.\.[0-9a-f]+ / aaaaaaa..bbbbbbb /'

echo "### list of branches"
git branch
